httpClient:
  timeout: 500ms
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  gzip:
    bufferSize: 8KiB
metrics:
  reporters:
    - type: console
      timeZone: UTC
      output: stdout
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
