httpClient:
  timeout: 500ms

http:
  maxIdleTime: 60s

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  gzip:
    bufferSize: 8KiB
